version: "3.7"

services:

  #Data persistence service layer
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: event
    volumes:
      - ./data:/var/lib/mysql
      - "./app/_sql:/docker-entrypoint-initdb.d"
      - "./app/_sql:/home/_sql"
    ports:
      - "3306:3306"

  #Application and web service layer
  php:
    build:
      context: ./
    restart: always
    volumes:
      - ./conf/php/:/usr/local/etc/php/
      - ./conf/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf 
      - ./app:/var/www/html
      - ./logs:/var/log/apache2
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mysql

  #Phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_PASSWORD: root
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mysql